function figmaAeImport(serialized) {
  try {
    var scene = JSON.parse(serialized);
    if (!scene || scene.version !== 1) throw new Error("Cena incompatível.");
    var appendMode = scene.importMode === "append";
    var comp = appendMode ? app.project.activeItem : app.project.items.addComp(scene.frame.name, scene.frame.width, scene.frame.height, 1, 10, 30);
    if (appendMode && !(comp && comp instanceof CompItem)) throw new Error("Abra e selecione uma composicao antes de enviar uma layer.");
    app.beginUndoGroup(appendMode ? "Adicionar layer do Figma" : "Importar frame do Figma");
    var skipped = 0, missingFonts = 0;
    for (var i = 0; i < scene.layers.length; i++) {
      var source = scene.layers[i];
      if (!source.visible || source.kind === "unsupported") { if (source.kind === "unsupported") skipped++; continue; }
      var layer;
      if (source.kind === "text") { var textResult = createText(comp, source); layer = textResult.layer; if (!textResult.fontMatched) missingFonts++; } else if (source.kind === "vector") layer = createVector(comp, source); else if (source.kind === "gradient") layer = createGradient(comp, source); else if (source.kind === "image") layer = createImage(comp, source, scene.exportId); else layer = createShape(comp, source);
      applyBlendMode(layer, source.blendMode);
      applyBlur(layer, source.blur);
    }
    if (!appendMode && scene.frame.color && !scene.frame.backgroundLayerIncluded) createBackground(comp, scene.frame.color, scene.frame.width, scene.frame.height);
    app.endUndoGroup();
    return (appendMode ? scene.layers.length + " layer(s) adicionada(s) a " + comp.name + ". " : "Composição criada: " + scene.frame.name + ". ") + skipped + " layer(s) não suportada(s) ignorada(s)." + (missingFonts ? " " + missingFonts + " fonte(s) não encontrada(s); foi usada a fonte padrão." : "");
  } catch (error) { try { app.endUndoGroup(); } catch (_) {} return "Erro: " + error.toString(); }
}
function rgba(color) { return color ? [color.r, color.g, color.b] : [0.5, 0.5, 0.5]; }
function applyBlendMode(layer, mode) { if (!layer || !mode) return; var modes = { NORMAL: BlendingMode.NORMAL, DARKEN: BlendingMode.DARKEN, MULTIPLY: BlendingMode.MULTIPLY, COLOR_BURN: BlendingMode.COLOR_BURN, LIGHTEN: BlendingMode.LIGHTEN, SCREEN: BlendingMode.SCREEN, COLOR_DODGE: BlendingMode.COLOR_DODGE, OVERLAY: BlendingMode.OVERLAY, SOFT_LIGHT: BlendingMode.SOFT_LIGHT, HARD_LIGHT: BlendingMode.HARD_LIGHT, DIFFERENCE: BlendingMode.DIFFERENCE, EXCLUSION: BlendingMode.EXCLUSION, HUE: BlendingMode.HUE, SATURATION: BlendingMode.SATURATION, COLOR: BlendingMode.COLOR, LUMINOSITY: BlendingMode.LUMINOSITY }; if (modes[mode] !== undefined) layer.blendingMode = modes[mode]; }
function applyBlur(layer, blur) { if (!layer || !blur || blur.type !== "LAYER_BLUR" || !blur.radius) return; var parade = layer.property("ADBE Effect Parade"); if (!parade) return; var effect = parade.addProperty("ADBE Gaussian Blur 2"); if (!effect) return; var amount = effect.property("ADBE Gaussian Blur 2-0001"); if (amount) amount.setValue(blur.radius); var repeat = effect.property("ADBE Gaussian Blur 2-0003"); if (repeat) repeat.setValue(false); }
function setTextTransform(layer, source) { if (!source.renderBounds) { setTransform(layer, source, true); return; } var bounds = layer.sourceRectAtTime(0, false); var group = layer.property("ADBE Transform Group"); group.property("ADBE Anchor Point").setValue([bounds.left + bounds.width / 2, bounds.top + bounds.height / 2]); group.property("ADBE Position").setValue([source.renderBounds.x + bounds.width / 2, source.renderBounds.y + bounds.height / 2]); group.property("ADBE Opacity").setValue(source.opacity * 100); group.property("ADBE Rotate Z").setValue(source.rotation); }
function setTransform(layer, source, includeExtents) { var bounds = layer.sourceRectAtTime(0, includeExtents === true); var group = layer.property("ADBE Transform Group"); group.property("ADBE Anchor Point").setValue([bounds.left + bounds.width / 2, bounds.top + bounds.height / 2]); group.property("ADBE Position").setValue([source.x + source.width / 2, source.y + source.height / 2]); group.property("ADBE Opacity").setValue(source.opacity * 100); group.property("ADBE Rotate Z").setValue(source.rotation); }
function setCenteredGeometryTransform(layer, source) { var group = layer.property("ADBE Transform Group"); group.property("ADBE Anchor Point").setValue([0, 0]); group.property("ADBE Position").setValue([source.x + source.width / 2, source.y + source.height / 2]); group.property("ADBE Opacity").setValue(source.opacity * 100); group.property("ADBE Rotate Z").setValue(source.rotation); }
function configureStroke(stroke, data, width) { stroke.property("ADBE Vector Stroke Color").setValue(rgba(data.color)); stroke.property("ADBE Vector Stroke Opacity").setValue(data.color.a * 100); stroke.property("ADBE Vector Stroke Width").setValue(width); var cap = { NONE: 1, ROUND: 2, SQUARE: 3 }[data.cap]; var join = { MITER: 1, ROUND: 2, BEVEL: 3 }[data.join]; if (cap) stroke.property("ADBE Vector Stroke Line Cap").setValue(cap); if (join) stroke.property("ADBE Vector Stroke Line Join").setValue(join); }
function addFillAndStroke(contents, source) { if (source.color) { var fill = contents.addProperty("ADBE Vector Graphic - Fill"); fill.property("ADBE Vector Fill Color").setValue(rgba(source.color)); fill.property("ADBE Vector Fill Opacity").setValue(source.color.a * 100); } if (source.stroke && !source.stroke.sides) { var stroke = contents.addProperty("ADBE Vector Graphic - Stroke"); configureStroke(stroke, source.stroke, source.stroke.width); } }
function sideOffset(align, width) { if (align === "INSIDE") return width / 2; if (align === "OUTSIDE") return -width / 2; return 0; }
function addStrokeSegment(root, source, side, width) { if (!width) return; var halfW = source.width / 2, halfH = source.height / 2, offset = sideOffset(source.stroke.align, width), a, b; if (side === "top") { a = [-halfW, -halfH + offset]; b = [halfW, -halfH + offset]; } else if (side === "right") { a = [halfW - offset, -halfH]; b = [halfW - offset, halfH]; } else if (side === "bottom") { a = [-halfW, halfH - offset]; b = [halfW, halfH - offset]; } else { a = [-halfW + offset, -halfH]; b = [-halfW + offset, halfH]; } var group = root.addProperty("ADBE Vector Group"), contents = group.property("ADBE Vectors Group"), path = contents.addProperty("ADBE Vector Shape - Group"), shape = new Shape(); shape.vertices = [a, b]; shape.inTangents = [[0, 0], [0, 0]]; shape.outTangents = [[0, 0], [0, 0]]; shape.closed = false; path.property("ADBE Vector Shape").setValue(shape); var stroke = contents.addProperty("ADBE Vector Graphic - Stroke"); configureStroke(stroke, source.stroke, width); }
function addIndividualStrokes(root, source) { if (!source.stroke || !source.stroke.sides) return; addStrokeSegment(root, source, "top", source.stroke.sides.top); addStrokeSegment(root, source, "right", source.stroke.sides.right); addStrokeSegment(root, source, "bottom", source.stroke.sides.bottom); addStrokeSegment(root, source, "left", source.stroke.sides.left); }
function createShape(comp, source) {
  var layer = comp.layers.addShape(); layer.name = source.name; var contents = layer.property("ADBE Root Vectors Group"); var group = contents.addProperty("ADBE Vector Group"); var shapes = group.property("ADBE Vectors Group");
  var needsClosedShape = !!source.color || !(source.stroke && source.stroke.sides);
  if (needsClosedShape && source.kind === "ellipse") { var ellipse = shapes.addProperty("ADBE Vector Shape - Ellipse"); ellipse.property("ADBE Vector Ellipse Size").setValue([source.width, source.height]); }
  else if (needsClosedShape) { var rect = shapes.addProperty("ADBE Vector Shape - Rect"); rect.property("ADBE Vector Rect Size").setValue([source.width, source.height]); rect.property("ADBE Vector Rect Roundness").setValue(Math.min(source.cornerRadius || 0, Math.min(source.width, source.height) / 2)); }
  addFillAndStroke(shapes, source); addIndividualStrokes(contents, source); setCenteredGeometryTransform(layer, source);
  return layer;
}
function gradientColor(stops, position) { if (!stops || !stops.length) return { r: 0, g: 0, b: 0, a: 1 }; if (position <= stops[0].position) return stops[0].color; if (position >= stops[stops.length - 1].position) return stops[stops.length - 1].color; for (var i = 0; i < stops.length - 1; i++) { var a = stops[i], b = stops[i + 1]; if (position >= a.position && position <= b.position) { var span = b.position - a.position, t = span ? (position - a.position) / span : 0; return { r: a.color.r + (b.color.r - a.color.r) * t, g: a.color.g + (b.color.g - a.color.g) * t, b: a.color.b + (b.color.b - a.color.b) * t, a: a.color.a + (b.color.a - a.color.a) * t }; } } return stops[stops.length - 1].color; }
function clipGradientPolygon(points, start, direction, threshold, greater) { var result = []; for (var i = 0; i < points.length; i++) { var current = points[i], previous = points[(i + points.length - 1) % points.length], currentValue = (current[0] - start[0]) * direction[0] + (current[1] - start[1]) * direction[1], previousValue = (previous[0] - start[0]) * direction[0] + (previous[1] - start[1]) * direction[1], currentInside = greater ? currentValue >= threshold : currentValue <= threshold, previousInside = greater ? previousValue >= threshold : previousValue <= threshold; if (currentInside !== previousInside) { var ratio = (threshold - previousValue) / (currentValue - previousValue); result.push([previous[0] + (current[0] - previous[0]) * ratio, previous[1] + (current[1] - previous[1]) * ratio]); } if (currentInside) result.push(current); } return result; }
function createGradient(comp, source) { var layer = comp.layers.addShape(); layer.name = source.name; var root = layer.property("ADBE Root Vectors Group"), data = source.gradient, transform = data.transform, width = source.width, height = source.height, start = [transform[0][2] * width - width / 2, transform[1][2] * height - height / 2], end = [(transform[0][0] + transform[0][2]) * width - width / 2, (transform[1][0] + transform[1][2]) * height - height / 2], direction = [end[0] - start[0], end[1] - start[1]], lengthSquared = direction[0] * direction[0] + direction[1] * direction[1]; if (!lengthSquared) { direction = [width, 0]; lengthSquared = width * width; } var corners = [[-width / 2, -height / 2], [width / 2, -height / 2], [width / 2, height / 2], [-width / 2, height / 2]], minT = 1e9, maxT = -1e9; for (var c = 0; c < corners.length; c++) { var t = ((corners[c][0] - start[0]) * direction[0] + (corners[c][1] - start[1]) * direction[1]) / lengthSquared; minT = Math.min(minT, t); maxT = Math.max(maxT, t); } var bands = 96, step = (maxT - minT) / bands; for (var i = 0; i < bands; i++) { var lowT = minT + i * step, highT = minT + (i + 1) * step, polygon = clipGradientPolygon(corners, start, direction, lowT * lengthSquared - 0.01, true); polygon = clipGradientPolygon(polygon, start, direction, highT * lengthSquared + 0.01, false); if (polygon.length < 3) continue; var color = gradientColor(data.stops, Math.max(0, Math.min(1, (lowT + highT) / 2))), group = root.addProperty("ADBE Vector Group"), contents = group.property("ADBE Vectors Group"), path = contents.addProperty("ADBE Vector Shape - Group"), shape = new Shape(), incoming = [], outgoing = []; for (var p = 0; p < polygon.length; p++) { incoming.push([0, 0]); outgoing.push([0, 0]); } shape.vertices = polygon; shape.inTangents = incoming; shape.outTangents = outgoing; shape.closed = true; path.property("ADBE Vector Shape").setValue(shape); var fill = contents.addProperty("ADBE Vector Graphic - Fill"); fill.property("ADBE Vector Fill Color").setValue([color.r, color.g, color.b]); fill.property("ADBE Vector Fill Opacity").setValue(color.a * data.opacity * 100); } setCenteredGeometryTransform(layer, source); return layer; }
function svgShape(pathData, width, height) { var tokens = pathData.match(/[a-zA-Z]|[-+]?(?:\d*\.?\d+)(?:[eE][-+]?\d+)?/g) || [], i = 0, command = "", x = 0, y = 0, startX = 0, startY = 0, vertices = [], inTangents = [], outTangents = [], closed = false; function number() { return parseFloat(tokens[i++]); } function point(relative) { var px = number(), py = number(); if (relative) { px += x; py += y; } return [px, py]; } function addVertex(p, incoming) { vertices.push([p[0] - width / 2, p[1] - height / 2]); inTangents.push(incoming || [0, 0]); outTangents.push([0, 0]); x = p[0]; y = p[1]; } while (i < tokens.length) { if (/[a-zA-Z]/.test(tokens[i])) command = tokens[i++]; if (!command) break; var relative = command === command.toLowerCase(), upper = command.toUpperCase(); if (upper === "Z") { closed = true; x = startX; y = startY; command = ""; continue; } if (upper === "M") { var move = point(relative); addVertex(move); startX = x; startY = y; command = relative ? "l" : "L"; continue; } if (upper === "L") { addVertex(point(relative)); continue; } if (upper === "H") { var hx = number(); if (relative) hx += x; addVertex([hx, y]); continue; } if (upper === "V") { var hy = number(); if (relative) hy += y; addVertex([x, hy]); continue; } if (upper === "C") { var cp1 = point(relative), cp2 = point(relative), end = point(relative); outTangents[outTangents.length - 1] = [cp1[0] - x, cp1[1] - y]; addVertex(end, [cp2[0] - end[0], cp2[1] - end[1]]); continue; } return null; } if (!vertices.length) return null; var shape = new Shape(); shape.vertices = vertices; shape.inTangents = inTangents; shape.outTangents = outTangents; shape.closed = closed; return shape; }
function scaleShape(shape, scaleX, scaleY) { var vertices = [], incoming = [], outgoing = []; for (var i = 0; i < shape.vertices.length; i++) { vertices.push([shape.vertices[i][0] * scaleX, shape.vertices[i][1] * scaleY]); incoming.push([shape.inTangents[i][0] * scaleX, shape.inTangents[i][1] * scaleY]); outgoing.push([shape.outTangents[i][0] * scaleX, shape.outTangents[i][1] * scaleY]); } shape.vertices = vertices; shape.inTangents = incoming; shape.outTangents = outgoing; return shape; }
function svgShapes(pathData, width, height, scaleX, scaleY) { var chunks = pathData.match(/[Mm][^Mm]*/g) || [pathData], result = []; for (var i = 0; i < chunks.length; i++) { var shape = svgShape(chunks[i], width, height); if (shape) result.push(scaleShape(shape, scaleX, scaleY)); } return result; }
function setVectorTransform(layer, source) { if (!source.vectorGeometry) { setTransform(layer, source); return; } var group = layer.property("ADBE Transform Group"); group.property("ADBE Anchor Point").setValue([0, 0]); group.property("ADBE Position").setValue([source.vectorGeometry.centerX, source.vectorGeometry.centerY]); group.property("ADBE Opacity").setValue(source.opacity * 100); group.property("ADBE Rotate Z").setValue(source.rotation); }
function createVector(comp, source) { var layer = comp.layers.addShape(); layer.name = source.name; var root = layer.property("ADBE Root Vectors Group"), paths = source.paths || [], geometry = source.vectorGeometry || { localWidth: source.width, localHeight: source.height, scaleX: 1, scaleY: 1 }; for (var i = 0; i < paths.length; i++) { var shapes = svgShapes(paths[i].data, geometry.localWidth, geometry.localHeight, geometry.scaleX, geometry.scaleY); if (!shapes.length) continue; var group = root.addProperty("ADBE Vector Group"), contents = group.property("ADBE Vectors Group"); for (var j = 0; j < shapes.length; j++) { var path = contents.addProperty("ADBE Vector Shape - Group"); path.property("ADBE Vector Shape").setValue(shapes[j]); } addFillAndStroke(contents, source); } setVectorTransform(layer, source); return layer; }
function decodeBase64(input) { var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/", output = "", buffer = 0, bits = 0; for (var i = 0; i < input.length; i++) { if (input.charAt(i) === "=") break; var value = alphabet.indexOf(input.charAt(i)); if (value < 0) continue; buffer = (buffer << 6) | value; bits += 6; if (bits >= 8) { bits -= 8; output += String.fromCharCode((buffer >> bits) & 255); buffer = bits ? buffer & ((1 << bits) - 1) : 0; } } return output; }
function safeFileName(value) { return String(value || "image").replace(/[^a-zA-Z0-9_-]/g, "_"); }
function createImage(comp, source, exportId) { if (!source.imageData) throw new Error("Imagem sem dados: " + source.name); var folder = new Folder(Folder.userData.fsName + "/FigmaAEBridge/assets"); if (!folder.exists && !folder.create()) throw new Error("Não foi possível criar a pasta de imagens."); var file = new File(folder.fsName + "/" + safeFileName(exportId) + "_" + safeFileName(source.id) + ".png"); file.encoding = "BINARY"; if (!file.open("w")) throw new Error("Não foi possível salvar a imagem: " + source.name); file.write(decodeBase64(source.imageData)); file.close(); var item = app.project.importFile(new ImportOptions(file)); var layer = comp.layers.add(item); layer.name = source.name; setTransform(layer, source); var transform = layer.property("ADBE Transform Group"); if (item.width && item.height) transform.property("ADBE Scale").setValue([source.width * 100 / item.width, source.height * 100 / item.height]); return layer; }
function applyFigmaFont(doc, source) { if (!source.fontFamily || !source.fontStyle || !app.fonts) return false; var fonts = app.fonts.getFontsByFamilyNameAndStyleName(source.fontFamily, source.fontStyle); if (!fonts || fonts.length === 0) return false; doc.fontObject = fonts[0]; return true; }
function applyVariableAxes(doc, source) { if (!doc.fontObject || !doc.fontObject.designAxesData) return; var axes = doc.fontObject.designAxesData, vector = doc.fontObject.designVector, changed = false; for (var i = 0; i < axes.length; i++) { var value; if (axes[i].tag === "opsz") value = source.fontSize || axes[i].default; else if (axes[i].tag === "wght" && source.fontWeight) value = source.fontWeight; else continue; vector[i] = Math.max(axes[i].min, Math.min(axes[i].max, value)); changed = true; } if (!changed) return; var postScriptName = doc.fontObject.postScriptNameForDesignVector(vector); var instances = app.fonts.getFontsByPostScriptName(postScriptName); if (instances && instances.length) doc.fontObject = instances[0]; }
function applyTextMetrics(doc, source) { var fontSize = source.fontSize || 16; if (source.letterSpacing) { var tracking = source.letterSpacing.unit === "PIXELS" ? source.letterSpacing.value * 1000 / fontSize : source.letterSpacing.value * 10; doc.tracking = Math.round(tracking); } if (source.lineHeight && source.lineHeight.unit !== "AUTO" && source.lineHeight.unit !== "INTRINSIC_%") { doc.autoLeading = false; doc.leading = source.lineHeight.unit === "PIXELS" ? source.lineHeight.value : fontSize * source.lineHeight.value / 100; } else doc.autoLeading = true; if (source.paragraphSpacing !== undefined) doc.spaceAfter = source.paragraphSpacing; if (source.paragraphIndent !== undefined) doc.firstLineIndent = source.paragraphIndent; }
function applyFigmaAlignment(doc, source) { if (source.textAlignHorizontal === "CENTER") doc.justification = ParagraphJustification.CENTER_JUSTIFY; else if (source.textAlignHorizontal === "RIGHT") doc.justification = ParagraphJustification.RIGHT_JUSTIFY; else if (source.textAlignHorizontal === "JUSTIFIED") doc.justification = ParagraphJustification.FULL_JUSTIFY_LASTLINE_LEFT; else doc.justification = ParagraphJustification.LEFT_JUSTIFY; }
function applyVerticalAlignment(doc, source) { if (!doc.boxText || typeof BoxVerticalAlignment === "undefined") return; if (source.textAlignVertical === "CENTER") doc.boxVerticalAlignment = BoxVerticalAlignment.CENTER; else if (source.textAlignVertical === "BOTTOM") doc.boxVerticalAlignment = BoxVerticalAlignment.BOTTOM; else doc.boxVerticalAlignment = BoxVerticalAlignment.TOP; }
function applyTextCase(text, textCase) { if (textCase === "UPPER") return text.toUpperCase(); if (textCase === "LOWER") return text.toLowerCase(); if (textCase === "TITLE") return text.replace(/\b\w/g, function(letter) { return letter.toUpperCase(); }); return text; }
function normalizeTextBreaks(text) { return String(text || "").replace(/[\u2028\u2029\r\n]+/g, "\r"); }
function applyTextGradient(layer, source) { try { var data = source.gradient; if (!data || !data.stops || data.stops.length < 2) return; var effects = layer.property("ADBE Effect Parade"), ramp = effects && effects.addProperty("ADBE Ramp"); if (!ramp) return; var first = data.stops[0].color, last = data.stops[data.stops.length - 1].color, matrix = data.transform, bounds = layer.sourceRectAtTime(0, false), width = source.width || bounds.width, height = source.height || bounds.height; ramp.property("ADBE Ramp-0001").setValue([bounds.left + matrix[0][2] * width, bounds.top + matrix[1][2] * height]); ramp.property("ADBE Ramp-0002").setValue(rgba(first)); ramp.property("ADBE Ramp-0003").setValue([bounds.left + (matrix[0][0] + matrix[0][2]) * width, bounds.top + (matrix[1][0] + matrix[1][2]) * height]); ramp.property("ADBE Ramp-0004").setValue(rgba(last)); } catch (_) {} }
function createText(comp, source) { var boxText = source.textAutoResize !== "WIDTH_AND_HEIGHT"; var layer = boxText ? comp.layers.addBoxText([Math.max(1, source.width), Math.max(1, source.height)]) : comp.layers.addText(); layer.name = source.name; var prop = layer.property("ADBE Text Properties").property("ADBE Text Document"); var doc = prop.value; doc.text = applyTextCase(source.text || "", source.textCase); var fontMatched = applyFigmaFont(doc, source); applyVariableAxes(doc, source); doc.fontSize = source.fontSize || 16; doc.applyFill = true; doc.fillColor = rgba(source.color); doc.autoKernType = AutoKernType.OPTICAL_KERN; applyFigmaAlignment(doc, source); applyVerticalAlignment(doc, source); applyTextMetrics(doc, source); prop.setValue(doc); setTransform(layer, source, boxText); return { layer: layer, fontMatched: fontMatched }; }
// Fast image import: the Node bridge materializes base64 before CEP receives the scene.
function createImage(comp, source, exportId) { if (!source.imagePath) throw new Error("Imagem sem arquivo: " + source.name); var file = new File(source.imagePath); if (!file.exists) throw new Error("Arquivo de imagem nao encontrado: " + source.name); var item = app.project.importFile(new ImportOptions(file)); var layer = comp.layers.add(item); layer.name = source.name; var transform = layer.property("ADBE Transform Group"); var uniformScale = item.width ? source.width * 100 / item.width : 100; var renderedWidth = item.width * uniformScale / 100; var renderedHeight = item.height * uniformScale / 100; transform.property("ADBE Anchor Point").setValue([item.width / 2, item.height / 2]); transform.property("ADBE Scale").setValue([uniformScale, uniformScale]); transform.property("ADBE Position").setValue([source.x + renderedWidth / 2, source.y + renderedHeight / 2]); transform.property("ADBE Opacity").setValue(source.opacity * 100); transform.property("ADBE Rotate Z").setValue(source.rotation); return layer; }
// Figma wraps greedily; AE's single-line composer is the closest editable-text equivalent.
function createText(comp, source) { var boxText = source.textAutoResize !== "WIDTH_AND_HEIGHT"; var fontSize = source.fontSize || 16; var widthSafety = boxText ? Math.max(4, fontSize * 0.35) : 0; var heightSafety = boxText ? Math.max(8, fontSize * 0.75) : 0; var boxWidth = Math.max(1, source.width + widthSafety); var boxHeight = Math.max(1, source.height + heightSafety); var layer = boxText ? comp.layers.addBoxText([boxWidth, boxHeight]) : comp.layers.addText(); layer.name = source.name; var prop = layer.property("ADBE Text Properties").property("ADBE Text Document"); var doc = prop.value; doc.text = applyTextCase(normalizeTextBreaks(source.text), source.textCase); var fontMatched = applyFigmaFont(doc, source); applyVariableAxes(doc, source); doc.fontSize = fontSize; doc.applyFill = true; doc.fillColor = rgba(source.color); doc.autoKernType = AutoKernType.OPTICAL_KERN; doc.everyLineComposer = false; doc.autoHyphenate = false; if (boxText) { doc.boxTextSize = [boxWidth, boxHeight]; if (typeof BoxAutoFitPolicy !== "undefined") doc.boxAutoFitPolicy = BoxAutoFitPolicy.NONE; if (typeof BoxFirstBaselineAlignment !== "undefined") doc.boxFirstBaselineAlignment = BoxFirstBaselineAlignment.CAP_HEIGHT; } applyFigmaAlignment(doc, source); applyVerticalAlignment(doc, source); applyTextMetrics(doc, source); prop.setValue(doc); setTextTransform(layer, source); applyTextGradient(layer, source); return { layer: layer, fontMatched: fontMatched }; }
// Native Gradient Fill. ExtendScript can set geometry but Adobe keeps the color-stop value inaccessible.
function createGradient(comp, source) { var layer = comp.layers.addShape(); layer.name = source.name; var root = layer.property("ADBE Root Vectors Group"), group = root.addProperty("ADBE Vector Group"), contents = group.property("ADBE Vectors Group"), rect = contents.addProperty("ADBE Vector Shape - Rect"), data = source.gradient, matrix = data.transform; rect.property("ADBE Vector Rect Size").setValue([source.width, source.height]); rect.property("ADBE Vector Rect Roundness").setValue(Math.min(source.cornerRadius || 0, Math.min(source.width, source.height) / 2)); var gradient = contents.addProperty("ADBE Vector Graphic - G-Fill"); gradient.property("ADBE Vector Grad Type").setValue(1); gradient.property("ADBE Vector Grad Start Pt").setValue([matrix[0][2] * source.width - source.width / 2, matrix[1][2] * source.height - source.height / 2]); gradient.property("ADBE Vector Grad End Pt").setValue([(matrix[0][0] + matrix[0][2]) * source.width - source.width / 2, (matrix[1][0] + matrix[1][2]) * source.height - source.height / 2]); gradient.property("ADBE Vector Fill Opacity").setValue(data.opacity * 100); if (source.stroke && !source.stroke.sides) { var stroke = contents.addProperty("ADBE Vector Graphic - Stroke"); configureStroke(stroke, source.stroke, source.stroke.width); } addIndividualStrokes(root, source); setCenteredGeometryTransform(layer, source); return layer; }
function overAEProjectFolder() { for (var i = 1; i <= app.project.numItems; i++) { var item = app.project.item(i); if (item instanceof FolderItem && item.parentFolder === app.project.rootFolder && item.name === "_OverAE") return item; } return app.project.items.addFolder("_OverAE"); }
function overAEDiskFolder() { var parent = app.project.file ? app.project.file.parent : new Folder(Folder.userData.fsName + "/OverAE/Unsaved Projects"); var folder = new Folder(parent.fsName + "/_OverAE"); if (!folder.exists && !folder.create()) throw new Error("Nao foi possivel criar a pasta _OverAE."); return folder; }
function importedFootageForFile(file) { for (var i = 1; i <= app.project.numItems; i++) { var item = app.project.item(i); if (item instanceof FootageItem && item.file && item.file.fsName === file.fsName) return item; } return null; }
function createImageMatte(comp, source, imageLayer) { if (!source.imageMask) return null; var data = source.imageMask, matteSource = { name: source.name + " · Mask", kind: data.kind, x: data.x, y: data.y, width: data.width, height: data.height, rotation: data.rotation || 0, opacity: 1, visible: true, color: { r: 1, g: 1, b: 1, a: 1 }, cornerRadius: data.cornerRadius || 0, paths: data.paths, vectorGeometry: data.vectorGeometry }, matte = data.kind === "vector" ? createVector(comp, matteSource) : createShape(comp, matteSource); matte.moveBefore(imageLayer); if (typeof imageLayer.setTrackMatte === "function") imageLayer.setTrackMatte(matte, TrackMatteType.ALPHA); else imageLayer.trackMatteType = TrackMatteType.ALPHA; return matte; }
function createImage(comp, source, exportId) { if (!source.imagePath) throw new Error("Imagem sem arquivo: " + source.name); var original = new File(source.imagePath); if (!original.exists) throw new Error("Arquivo de imagem nao encontrado: " + source.name); var diskFolder = overAEDiskFolder(), file = new File(diskFolder.fsName + "/" + original.name); if (!file.exists && !original.copy(file.fsName)) throw new Error("Nao foi possivel copiar o asset para _OverAE: " + source.name); var item = importedFootageForFile(file); if (!item) item = app.project.importFile(new ImportOptions(file)); item.parentFolder = overAEProjectFolder(); var layer = comp.layers.add(item); layer.name = source.name; var transform = layer.property("ADBE Transform Group"), placement = source.imagePlacement; transform.property("ADBE Anchor Point").setValue([item.width / 2, item.height / 2]); if (placement) { transform.property("ADBE Scale").setValue([placement.scaleX * 100, placement.scaleY * 100]); transform.property("ADBE Position").setValue([placement.centerX, placement.centerY]); transform.property("ADBE Rotate Z").setValue(placement.rotation); } else { var uniformScale = item.width ? source.width * 100 / item.width : 100, renderedWidth = item.width * uniformScale / 100, renderedHeight = item.height * uniformScale / 100; transform.property("ADBE Scale").setValue([uniformScale, uniformScale]); transform.property("ADBE Position").setValue([source.x + renderedWidth / 2, source.y + renderedHeight / 2]); transform.property("ADBE Rotate Z").setValue(source.rotation); } transform.property("ADBE Opacity").setValue(source.opacity * 100); createImageMatte(comp, source, layer); return layer; }
function createBackground(comp, color, width, height) { var source = { name: "Background", kind: "rectangle", x: 0, y: 0, width: width, height: height, rotation: 0, opacity: color.a === undefined ? 1 : color.a, color: color }; var layer = createShape(comp, source); layer.moveToEnd(); }
function overAEProjectReferencesFile(filePath) { for (var i = 1; i <= app.project.numItems; i++) { var item = app.project.item(i); if (item instanceof FootageItem && item.file && item.file.fsName === filePath) return true; } return false; }
function overAECleanupUnused() { try { var folder = overAEProjectFolder(), managedDiskFolder = overAEDiskFolder(), removable = [], filePaths = [], i; for (i = 1; i <= folder.numItems; i++) { var item = folder.item(i); if (item instanceof FootageItem && (!item.usedIn || item.usedIn.length === 0)) removable.push(item); } if (!removable.length) return "Nenhuma footage sem uso encontrada."; app.beginUndoGroup("Limpar assets sem uso do OverAE"); for (i = removable.length - 1; i >= 0; i--) { var footage = removable[i]; if (footage.file && footage.file.parent && footage.file.parent.fsName === managedDiskFolder.fsName) filePaths.push(footage.file.fsName); footage.remove(); } app.endUndoGroup(); var deletedFiles = 0; for (i = 0; i < filePaths.length; i++) { if (overAEProjectReferencesFile(filePaths[i])) continue; var file = new File(filePaths[i]); if (file.exists && file.parent.fsName === managedDiskFolder.fsName && file.remove()) deletedFiles++; } return removable.length + " footage(s) sem uso removida(s); " + deletedFiles + " arquivo(s) apagado(s) da pasta _OverAE."; } catch (error) { try { app.endUndoGroup(); } catch (_) {} return "Erro ao limpar: " + error.toString(); } }
